---
abstract: 'Perl Port of Kage'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.02
  Module::Build::Pluggable::Repository: 0.01
  Pod::Markdown: 0
configure_requires:
  Module::Build: 0.40
  Module::Build::Pluggable: 0.05
  Module::Build::Pluggable::ReadmeMarkdownFromPod: 0.02
  Module::Build::Pluggable::Repository: 0.01
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geest
provides:
  Geest:
    file: lib/Geest.pm
    version: 0.02
  Geest::Backend:
    file: lib/Geest/Backend.pm
    version: 0
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  AnyEvent::Socket: 0
  HTTP::Message::PSGI: 0
  HTTP::Request: 0
  HTTP::Response: 0
  Log::Minimal: 0
  Moo: 1.000008
  Plack::Request: 0
  Twiggy: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/lestrrat/p5-Geest.git
version: 0.02
